version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8001 core.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - djangodb
    restart: unless-stopped
    networks:
      - my_net

  djangodb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - my_net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my_net:
    external: true